-- Topic 6: HQ And DML, DDL Extension
-- Assignment: 3

INSERT ALL INTO SAL_HISTORY(EMPID, HIREDATE, SAL)
VALUES(EMPID, HIREDATE, SAL) INTO MGR_HISTORY(EMPID, MGR_ID, HIREDATE)
VALUES(EMPID, MGR_ID, HIREDATE)
SELECT EMPNO,
    MGR,
    SAL,
    HIREDATE
FROM EMPLOYEE;
